### ISSUE TITLE
Banner does not show keycloak version

### ISSUE THREAD

**Issue by ebremer** [thomasdarimont/embedded-spring-boot-keycloak-server#34]
https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/blob/master/embedded-keycloak-server-custom/src/main/resources/banner.txt

Shows as:

  _  __                        _                   _     __   __   __
 | |/ /   ___   _   _    ___  | |   ___     __ _  | | __ \ \  \ \  \ \
 | ' /   / _ \ | | | |  / __| | |  / _ \   / _` | | |/ /  \ \  \ \  \ \
 | . \  |  __/ | |_| | | (__  | | | (_) | | (_| | |   <   / /  / /  / /
 |_|\_\  \___|  \__, |  \___| |_|  \___/   \__,_| |_|\_\ /_/  /_/  /_/
                |___/

Spring Boot Version:  (v2.3.3.RELEASE)
Keycloak Version: (v@keycloak.version@)

**Comment by netmikey** [comment]
I had a look into this already. It seems that the banner is rendered into the console in a very early stage of the Spring Boot startup process. No other Spring Boot modules (not even the configuration properties) have been loaded when it is displayed. Only very few variables are available at the time the banner is rendered (e.g. the Spring Boot version).

I guess there's no way to render the Keycloak version into the banner at runtime. Rendering it into a static banner file wouldn't be satisfactory either because that version wouldn't reflect the real Keycloak version if someone choses to include another one at runtime than the one this project was built with.

The easiest would be not putting any keycloak version into the banner and print it in an INFO log at startup (there might already be such a log entry, not sure right now).
